# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demi < Formula
  desc "Project maintenance tool for developers"
  homepage "https://github.com/wroog-com/demiurge"
  version "0.2.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/wroog-com/demiurge/releases/download/v0.2.1/demiurge_0.2.1_darwin_amd64.zip"
    sha256 "ce4f764c8f0281e14a59866cf0fa969447c267f92953f583f2972c0b94dba99b"

    define_method(:install) do
      bin.install "demi"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/wroog-com/demiurge/releases/download/v0.2.1/demiurge_0.2.1_darwin_arm64.zip"
    sha256 "3a96e17d499632be1dee90841068d41a412b9eaf182ac983ec6c6099c1152404"

    define_method(:install) do
      bin.install "demi"
    end
  end
end
