# This file was generated by GoReleaser. DO NOT EDIT.
cask "demi" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "eb788f2518a84b364068b25b84ce76178c6d8d937d80b65efad15ec9fe1c84c1"
      url "https://github.com/wroog-com/demiurge/releases/download/v#{version}/demiurge_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "8f00b680ea662787770ddbab659c6e22d925358c66389380844e0874f75acd02"
      url "https://github.com/wroog-com/demiurge/releases/download/v#{version}/demiurge_#{version}_darwin_arm64.zip"
    end
  end

  name "demi"
  desc "Project maintenance tool for developers"
  homepage "https://github.com/wroog-com/demiurge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "demi"

  # No zap stanza required

end
