# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demi < Formula
  desc "Project maintenance tool for developers"
  homepage "https://github.com/wroog-com/demiurge"
  version "0.6.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/wroog-com/demiurge/releases/download/v0.6.0/demiurge_0.6.0_darwin_amd64.zip"
    sha256 "0f9acc0a258160b15bd3550017b667176d3f1a8ac3d4067cb76aaabd13f141bf"

    define_method(:install) do
      bin.install "demi"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/wroog-com/demiurge/releases/download/v0.6.0/demiurge_0.6.0_darwin_arm64.zip"
    sha256 "10b3c03da83980244a163b639b3537c485475cc8b0e7fa86027d5ffb54556fe2"

    define_method(:install) do
      bin.install "demi"
    end
  end
end
